'use strict';
const {variants}=require('./campaignConfig');
const {esc}=require('./marketing');
function section(html,name){return html.split(`<!-- shared:${name}:start -->`)[1]?.split(`<!-- shared:${name}:end -->`)[0]||'';}
function landingPage(home,variant='ahorro') {
  const key=Object.hasOwn(variants,variant)?variant:'ahorro',v=variants[key];
  const intro=`<div class="auction-explainer"><h2 data-i18n="lpExplain">Las subastas, en 3 frases</h2><ol><li data-i18n="lpExplain1">Copart vende cada semana miles de autos de aseguradoras, bancos y flotas por debajo del precio al público.</li><li data-i18n="lpExplain2">Muchos lotes solo admiten pujas de compradores con licencia. APV Motors la tiene.</li><li data-i18n="lpExplain3">Evaluamos el auto, te damos el costo y pujamos por ti hasta el tope que tú apruebas.</li></ol><p data-i18n="lpRisk">Muchos de estos autos tienen daño o título de salvamento. Por eso revisamos cada uno contigo antes de pujar.</p></div>`;
  let featured=section(home,'featured').replace('<section ', '<section id="autos" ');
  featured += '<p class="lp-range-link"><a id="lp-range-link" href="/catalogo" data-i18n="lpBrowseAll">Ver todos los autos disponibles →</a></p>';
  const steps=`<section class="lp-steps wrap" id="como-funciona"><h2 data-i18n="lpSteps">Así compras, en 4 pasos</h2><ol>${[['Elige el auto y revisa los costos','Explora sin registrarte. Guarda tus favoritos y revisa cada ficha antes de decidir.'],['Confirma tu depósito reembolsable','Tu asesor confirma el monto y las condiciones antes de pujar.'],['Nosotros gestionamos la puja','Pujamos hasta el tope que tú apruebas y te acompañamos durante el proceso.'],['Pago, documentación y transporte','Si ganas, pagas el vehículo por transferencia y coordinamos los siguientes pasos contigo.']].map(([title,body],i)=>`<li><span aria-hidden="true">${i+1}</span><div><h3 data-i18n="lpStep${i+1}">${title}</h3><p data-i18n="lpStep${i+1}Body">${body}</p></div></li>`).join('')}</ol></section>`;
  const budget=section(home,'budget').replace('data-i18n="marketing_61"','data-i18n="lpBudgetTitle"');
  const trust=`<section class="lp-trust wrap"><h2 data-i18n="lpTrust">El respaldo de APV Motors</h2><div><article><h3 data-i18n="lpTrust1">Acompañamiento en español</h3><p data-i18n="lpTrust1Body">Un asesor te ayuda a revisar el auto y los costos antes de pujar.</p></article><article><h3 data-i18n="lpTrust2">De la puja a la entrega</h3><p data-i18n="lpTrust2Body">Coordinamos contigo el pago, la documentación y el transporte.</p></article></div></section>`;
  const faq=section(home,'faq').replace(/<a[^>]*href="https:\/\/wa\.me\/[^"]*"[\s\S]*?<\/a>/g,'').replace(/<details(?![^>]*data-key-faq)[\s\S]*?<\/details>/g,'');
  const compactCosts=section(home,'costs')
    .replace(/<p[^>]*>(?:(?!<\/p>)[\s\S])*?href="#planes"(?:(?!<\/p>)[\s\S])*?<\/p>/g,'')
    .replace(/<a[^>]*href="#presupuesto"[\s\S]*?<\/a>/,'').replace(/<a[^>]*href="https:\/\/wa\.me\/[^"]*"[\s\S]*?<\/a>/g,'');
  const main=`<main class="home-content"><section class="lp-hero wrap"><div class="lp-hero-copy"><p class="eyebrow" data-i18n="variant_${key}_eyebrow">${esc(v.eyebrow)}</p><h1 data-i18n="variant_${key}_title">${esc(v.title)}</h1><p class="lead" data-i18n="variant_${key}_subtitle">${esc(v.subtitle)}</p><div class="lp-entry"><p data-i18n="lpStart">¿Cómo quieres empezar?</p><div><a href="#lp-explain" data-cta="lp-first"><strong data-i18n="lpNew">Es mi primera vez</strong><span data-i18n="lpNewNote">Explícame cómo funciona</span></a><a href="#presupuesto" data-cta="lp-experienced"><strong data-i18n="lpKnown">Ya conozco las subastas</strong><span data-i18n="lpKnownNote">Quiero buscar mi auto</span></a></div></div><div class="hero-assurances"><span data-live-rating hidden></span><span data-i18n="lpDeposit">Depósito reembolsable</span><span data-i18n="lpAdvisor">Asesor humano</span></div><a class="btn btn-primary" href="#autos" data-cta="lp-hero" data-i18n="lpCta">Ver autos en subasta →</a></div>${section(home,'video')}</section><section class="wrap lp-explainer" id="lp-explain">${intro}</section>${budget}${featured}${steps}${compactCosts}${trust}${section(home,'evaluation')}${section(home,'reviews')}${faq}<section class="final-cta wrap"><div><h2 data-i18n="lpFinal">Encuentra tu auto hoy</h2></div><div class="final-actions"><a class="button white" href="#autos" data-cta="lp-final" data-i18n="lpCta">Ver autos en subasta →</a><a href="https://wa.me/13462048308" data-cta="lp-final" class="final-whatsapp" data-i18n="lpQuestions">¿Tienes dudas? Escríbenos ↗</a></div></section><div hidden inert>${section(home,'hooks')}${section(home,'catalog')}</div></main><a class="lp-sticky btn btn-primary" href="#autos" data-cta="lp-sticky" data-i18n="lpCta">Ver autos en subasta →</a>`;
  return home.replace('<body class="home-page"','<body class="home-page lp-page" data-variant="'+key+'"')
    .replace(/<main>[\s\S]*?<\/main>/,main)
    .replace(/(<header[\s\S]*?<\/header>)/,header=>'<div hidden inert>'+header.replace(/<nav[\s\S]*?<\/nav>/,'')+'</div><div class="lp-brand wrap"><img src="/assets/apv-logo-red.png" alt="APV Motors" width="130" height="64"></div>')
    .replace(/(<form[^>]*id="sticky-search"[\s\S]*?<\/form>)/,'<div hidden inert>$1</div>');
}
module.exports=landingPage;
